name: bloom_trace_root
description: "Root helper pubspec to make package: imports resolve in workspace"
publish_to: 'none'

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.0
  firebase_messaging: ^15.2.10
  cloud_firestore: ^5.6.12
  google_generative_ai: ^0.4.0
  mobile_scanner: ^7.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
